#!/bin/dash

# part-hotplug-handler: a handler executed by part-hotplug-monitor when a
#                       partition-related event occurs; the partition details
#                       (e.g its name) are passed through the environment

case "$ACTION" in
	add)
		# add a pinboard icon
		exec part-icon add "${DEVNAME##*/}" "$DEVNAME"
		;;

	remove)
		# remove the partition icon
		exec part-icon remove "${DEVNAME##*/}"
		;;

	change)
		# when a change event occurs, do nothing
		;;
esac